// Style Dictionary build for @tourism/tokens.
// Emits generated/tokens.css (Tailwind v4 @theme inline + :root + .dark).
// Run: node libs/shared/tokens/style-dictionary/build.mjs (wired as the Nx `tokens` target).

import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { remToDp, toRnColor, toRnScale } from './rn-convert.js';
import tokens, {
  baseRules,
  densityCompact,
  fonts,
  radiusScale,
  regionDefaults,
  rootExtras,
  themeExtras,
} from './tokens.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../generated');

const HEADER =
  '/* GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand. */\n' +
  '/* Source: libs/shared/tokens/style-dictionary/ */';

const cssVar = (token) => `--${token.path.slice(1).join('-')}`;
const radiusStep = (mult) => (mult === 1 ? 'var(--radius)' : `calc(var(--radius) * ${mult})`);

StyleDictionary.registerFormat({
  name: 'tourism/tailwind-css',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const radius = dictionary.allTokens.find((t) => t.path[0] === 'radius');

    const theme = [
      `  --font-heading: ${fonts.heading};`,
      `  --font-sans: ${fonts.sans};`,
      ...colors.map((t) => `  --color-${t.path.slice(1).join('-')}: var(${cssVar(t)});`),
      ...Object.entries(radiusScale).map(([s, m]) => `  --radius-${s}: ${radiusStep(m)};`),
      ...themeExtras.map(([k, v]) => `  ${k}: ${v};`),
    ];
    const root = [
      ...colors.map((t) => `  ${cssVar(t)}: ${t.original.value};`),
      `  --radius: ${radius.original.value};`,
      ...rootExtras.map(([k, v]) => `  ${k}: ${v};`),
      // Slot region mặc định = brand — trang không gắn data-region không đổi gì (ADR-0013 #3).
      ...Object.entries(regionDefaults).map(([k, v]) => `  --region-${k}: ${v};`),
    ];
    const dark = colors.map((t) => `  ${cssVar(t)}: ${t.original.darkValue};`);

    return [
      HEADER,
      '',
      '@theme inline {',
      ...theme,
      '}',
      '',
      ':root {',
      ...root,
      '}',
      '',
      '.dark {',
      ...dark,
      '}',
      '',
      // ADR-0015: ba khối override `[data-region='north'|'central'|'south']` đã
      // XOÁ (Task 5i) — `regionDefaults` ở `:root` trên là giá trị --region-*
      // DUY NHẤT còn lại, không còn override theo vùng nào nữa.
      "[data-density='compact'] {",
      ...densityCompact.map(([k, v]) => `  ${k}: ${v};`),
      '}',
      '',
      '@layer base {',
      ...baseRules.map((l) => `  ${l}`),
      '}',
      '',
    ].join('\n');
  },
});

// React Native theme — hex colors + dp radius, consumed by @tourism/mobile-ui.
StyleDictionary.registerFormat({
  name: 'tourism/rn-theme',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const radius = dictionary.allTokens.find((t) => t.path[0] === 'radius');
    const key = (t) => t.path.slice(1).join('-');
    const entries = (pick) =>
      colors.map((t) => `      '${key(t)}': '${toRnColor(pick(t))}',`).join('\n');

    // Phần phi-màu (type scale, font weight, spacing, touch target) — mobile
    // không có Tailwind đọc `--text-*`, nên phải đi qua cầu này thay vì viết
    // tay con số trong component (CLAUDE.md #6 áp cho mobile y như web).
    const scale = toRnScale(themeExtras, rootExtras);
    const indent = (value, pad) =>
      JSON.stringify(value, null, 2)
        .split('\n')
        .map((line, i) => (i === 0 ? line : pad + line))
        .join('\n');

    return [
      '// GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand.',
      '// RN theme — hex colors (converted from oklch) + dp radius/type/spacing.',
      'export const theme = {',
      '  colors: {',
      '    light: {',
      entries((t) => t.original.value),
      '    },',
      '    dark: {',
      entries((t) => t.original.darkValue),
      '    },',
      '  },',
      `  radius: { base: ${remToDp(radius.original.value)} },`,
      `  type: ${indent(scale.type, '  ')},`,
      `  weight: ${indent(scale.weight, '  ')},`,
      `  spacing: ${scale.spacing},`,
      `  touchTargetMin: ${scale.touchTargetMin},`,
      '};',
      '',
      'export default theme;',
      '',
    ].join('\n');
  },
});

// Type surface for the generated theme.js (emitted together so they stay in lockstep).
StyleDictionary.registerFormat({
  name: 'tourism/rn-theme-dts',
  format: () =>
    [
      '// GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand.',
      'export interface RnTypeStep {',
      '  fontSize: number;',
      '  lineHeight: number;',
      '}',
      'export interface RnTheme {',
      '  colors: {',
      '    light: Record<string, string>;',
      '    dark: Record<string, string>;',
      '  };',
      '  radius: { base: number };',
      '  /** Type scale theo dp — khoá là bậc Tailwind (xs, sm, base, lg, …). */',
      '  type: Record<string, RnTypeStep>;',
      '  /** Font weight dạng chuỗi mà React Native nhận ("400", "600", …). */',
      '  weight: Record<string, string>;',
      '  /** Bước spacing gốc theo dp (Tailwind nhân bội số từ đây). */',
      '  spacing: number;',
      '  /** Cạnh tối thiểu của vùng chạm, theo dp (a11y). */',
      '  touchTargetMin: number;',
      '}',
      'export declare const theme: RnTheme;',
      'export default theme;',
      '',
    ].join('\n'),
});

const sd = new StyleDictionary({
  tokens,
  log: { verbosity: 'silent' },
  platforms: {
    tailwind: {
      // No value transforms — emit oklch strings verbatim; names come from token paths.
      transforms: [],
      buildPath: `${outDir}/`,
      files: [
        { destination: 'tokens.css', format: 'tourism/tailwind-css' },
        { destination: 'theme.js', format: 'tourism/rn-theme' },
        { destination: 'theme.d.ts', format: 'tourism/rn-theme-dts' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log(`tokens.css written to ${outDir}`);
