// Style Dictionary build for @tourism/tokens.
// Emits generated/tokens.css (Tailwind v4 @theme inline + :root + .dark).
// Run: node libs/shared/tokens/style-dictionary/build.mjs (wired as the Nx `tokens` target).

import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { remToDp, toRnColor } from './rn-convert.js';
import tokens, {
  baseRules,
  densityCompact,
  fonts,
  radiusScale,
  rootExtras,
  themeExtras,
} from './tokens.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../generated');

const HEADER =
  '/* GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand. */\n' +
  '/* Source: libs/shared/tokens/style-dictionary/ */';

const cssVar = (token) => `--${token.path.slice(1).join('-')}`;
const radiusStep = (mult) => (mult === 1 ? 'var(--radius)' : `calc(var(--radius) * ${mult})`);

StyleDictionary.registerFormat({
  name: 'tourism/tailwind-css',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const radius = dictionary.allTokens.find((t) => t.path[0] === 'radius');

    const theme = [
      `  --font-heading: ${fonts.heading};`,
      `  --font-sans: ${fonts.sans};`,
      ...colors.map((t) => `  --color-${t.path.slice(1).join('-')}: var(${cssVar(t)});`),
      ...Object.entries(radiusScale).map(([s, m]) => `  --radius-${s}: ${radiusStep(m)};`),
      ...themeExtras.map(([k, v]) => `  ${k}: ${v};`),
    ];
    const root = [
      ...colors.map((t) => `  ${cssVar(t)}: ${t.original.value};`),
      `  --radius: ${radius.original.value};`,
      ...rootExtras.map(([k, v]) => `  ${k}: ${v};`),
    ];
    const dark = colors.map((t) => `  ${cssVar(t)}: ${t.original.darkValue};`);

    return [
      HEADER,
      '',
      '@theme inline {',
      ...theme,
      '}',
      '',
      ':root {',
      ...root,
      '}',
      '',
      '.dark {',
      ...dark,
      '}',
      '',
      "[data-density='compact'] {",
      ...densityCompact.map(([k, v]) => `  ${k}: ${v};`),
      '}',
      '',
      '@layer base {',
      ...baseRules.map((l) => `  ${l}`),
      '}',
      '',
    ].join('\n');
  },
});

// React Native theme — hex colors + dp radius, consumed by @tourism/mobile-ui.
StyleDictionary.registerFormat({
  name: 'tourism/rn-theme',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const radius = dictionary.allTokens.find((t) => t.path[0] === 'radius');
    const key = (t) => t.path.slice(1).join('-');
    const entries = (pick) =>
      colors.map((t) => `      '${key(t)}': '${toRnColor(pick(t))}',`).join('\n');

    return [
      '// GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand.',
      '// RN theme — hex colors (converted from oklch) + dp radius.',
      'export const theme = {',
      '  colors: {',
      '    light: {',
      entries((t) => t.original.value),
      '    },',
      '    dark: {',
      entries((t) => t.original.darkValue),
      '    },',
      '  },',
      `  radius: { base: ${remToDp(radius.original.value)} },`,
      '};',
      '',
      'export default theme;',
      '',
    ].join('\n');
  },
});

// Type surface for the generated theme.js (emitted together so they stay in lockstep).
StyleDictionary.registerFormat({
  name: 'tourism/rn-theme-dts',
  format: () =>
    [
      '// GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand.',
      'export interface RnTheme {',
      '  colors: {',
      '    light: Record<string, string>;',
      '    dark: Record<string, string>;',
      '  };',
      '  radius: { base: number };',
      '}',
      'export declare const theme: RnTheme;',
      'export default theme;',
      '',
    ].join('\n'),
});

const sd = new StyleDictionary({
  tokens,
  log: { verbosity: 'silent' },
  platforms: {
    tailwind: {
      // No value transforms — emit oklch strings verbatim; names come from token paths.
      transforms: [],
      buildPath: `${outDir}/`,
      files: [
        { destination: 'tokens.css', format: 'tourism/tailwind-css' },
        { destination: 'theme.js', format: 'tourism/rn-theme' },
        { destination: 'theme.d.ts', format: 'tourism/rn-theme-dts' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log(`tokens.css written to ${outDir}`);
